services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "110:111"
    network_mode: 'host'
    volumes:
      - /opt/jellyfin/config:/config
      - /opt/jellyfin/cache:/cache
      - type: bind
        source: /mnt/pool/samba/users/family/Media/Entertainment
        target: /media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin:8096

